# LOCAL CONNECTION (output as SQL output)

In [3]:
#If you haven't installed it already (either by using pip or by anaconda), run the following command in a Jupyter Notebook cell to install the extension
#!pip install ipython-sql (i have commented it out since we already downloaded ipython-sql from anaconda)

In [4]:
#In a Jupyter Notebook cell, load the %sql extension using the %load_ext magic command:
%load_ext sql

In [5]:
#Use the %sql magic command to connect to your SQLite database. 
#Replace your_database.db with the actual path to your SQLite database file. 
#Use forward slashes (/) as path separators even on Windows:
#db_path="C:/Users/DELL/Documents/All%20Files/ALX Academy/Data%20Science/SQL/SQL%20Files/Extracted%20Module-3-SQL-a-3902/Module%203_%20SQL/Exercises/chinook.db"
#db_path = "C:/Users/DELL/Documents/All Files/ALX Academy/Data Science/SQL/SQL Files/Extracted Module-3-SQL-a-3902/Module 3_ SQL/Exercises/chinook.db"
#%sql sqlite:///C:/Users/DELL/Documents/All%20Files/ALX%20Academy/Data%20Science/SQL/SQL%20Files/ALX%20SQL%20Tutorial1/Module3_%20SQL/Exercises/chinook.db

%sql sqlite:///chinook.db

'Connected: @chinook.db'

In [24]:
#This "%sql postgresql:///chinook.db" wont work for PostgreSQL does not use a single file for the entire database in the same way that SQLite does. Therefore, you cannot directly reference a "database filename" in the connection string as you might with SQLite.
#In PostgreSQL, you need to provide connection details such as the username, password, host, port, and database name in the connection string. The connection string format for PostgreSQL is typically:


#postgresql://username:password@host:port/database

In [7]:
#checking the table names in chinook database
#%sql SELECT name FROM sqlite_master WHERE type='table';

In [25]:
-- This is a single-line comment (SQL will not execute lines that begin with '--')

/* This is a block
comment which will comment
multiple lines
*/

SyntaxError: invalid syntax (1299474431.py, line 1)

In [8]:
#Showing all tables present in the Chinook database
%sql SELECT name FROM sqlite_master WHERE type='table';

 * sqlite:///chinook.db
Done.

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',)]

In [9]:
#You can now execute SQL commands using the %sql magic command. For example, to retrieve data from a table:
#%reload_ext sql
#%sql SELECT * FROM "employees";
%sql SELECT * FROM employees LIMIT 10;

 * sqlite:///chinook.db
Done.

[(1, 'Adams', 'Andrew', 'General Manager', None, '1962-02-18 00:00:00', '2002-08-14 00:00:00', '11120 Jasper Ave NW', 'Edmonton', 'AB', 'Canada', 'T5K 2N1', '+1 (780) 428-9482', '+1 (780) 428-3457', 'andrew@chinookcorp.com'),
 (2, 'Edwards', 'Nancy', 'Sales Manager', 1, '1958-12-08 00:00:00', '2002-05-01 00:00:00', '825 8 Ave SW', 'Calgary', 'AB', 'Canada', 'T2P 2T3', '+1 (403) 262-3443', '+1 (403) 262-3322', 'nancy@chinookcorp.com'),
 (3, 'Peacock', 'Jane', 'Sales Support Agent', 2, '1973-08-29 00:00:00', '2002-04-01 00:00:00', '1111 6 Ave SW', 'Calgary', 'AB', 'Canada', 'T2P 5M5', '+1 (403) 262-3443', '+1 (403) 262-6712', 'jane@chinookcorp.com'),
 (4, 'Park', 'Margaret', 'Sales Support Agent', 2, '1947-09-19 00:00:00', '2003-05-03 00:00:00', '683 10 Street SW', 'Calgary', 'AB', 'Canada', 'T2P 5G3', '+1 (403) 263-4423', '+1 (403) 263-4289', 'margaret@chinookcorp.com'),
 (5, 'Johnson', 'Steve', 'Sales Support Agent', 2, '1965-03-03 00:00:00', '2003-10-17 00:00:00', '7727B 41 Ave', 'Calgary', 'AB', 'Canada', 'T3B 1Y7', '1 (780) 836-9987', '1 (780) 836-9543', 'steve@chinookcorp.com'),
 (6, 'Mitchell', 'Michael', 'IT Manager', 1, '1973-07-01 00:00:00', '2003-10-17 00:00:00', '5827 Bowness Road NW', 'Calgary', 'AB', 'Canada', 'T3B 0C5', '+1 (403) 246-9887', '+1 (403) 246-9899', 'michael@chinookcorp.com'),
 (7, 'King', 'Robert', 'IT Staff', 6, '1970-05-29 00:00:00', '2004-01-02 00:00:00', '590 Columbia Boulevard West', 'Lethbridge', 'AB', 'Canada', 'T1K 5N8', '+1 (403) 456-9986', '+1 (403) 456-8485', 'robert@chinookcorp.com'),
 (8, 'Callahan', 'Laura', 'IT Staff', 6, '1968-01-09 00:00:00', '2004-03-04 00:00:00', '923 7 ST NW', 'Lethbridge', 'AB', 'Canada', 'T1H 1Y8', '+1 (403) 467-3351', '+1 (403) 467-8772', 'laura@chinookcorp.com')]

In [10]:
%%sql
SELECT 
    FirstName,
    LastName,
    Title
FROM employees
WHERE Country = 'Canada' 
AND City = 'Calgary'
AND ReportsTo IS NOT NULL
LIMIT 10;

 * sqlite:///chinook.db
Done.

[('Nancy', 'Edwards', 'Sales Manager'),
 ('Jane', 'Peacock', 'Sales Support Agent'),
 ('Margaret', 'Park', 'Sales Support Agent'),
 ('Steve', 'Johnson', 'Sales Support Agent'),
 ('Michael', 'Mitchell', 'IT Manager')]

In [11]:
%sql SELECT * FROM invoices LIMIT 10;

 * sqlite:///chinook.db
Done.

[(1, 2, '2009-01-01 00:00:00', 'Theodor-Heuss-Straße 34', 'Stuttgart', None, 'Germany', '70174', 1.98),
 (2, 4, '2009-01-02 00:00:00', 'Ullevålsveien 14', 'Oslo', None, 'Norway', '0171', 3.96),
 (3, 8, '2009-01-03 00:00:00', 'Grétrystraat 63', 'Brussels', None, 'Belgium', '1000', 5.94),
 (4, 14, '2009-01-06 00:00:00', '8210 111 ST NW', 'Edmonton', 'AB', 'Canada', 'T6G 2C7', 8.91),
 (5, 23, '2009-01-11 00:00:00', '69 Salem Street', 'Boston', 'MA', 'USA', '2113', 13.86),
 (6, 37, '2009-01-19 00:00:00', 'Berger Straße 10', 'Frankfurt', None, 'Germany', '60316', 0.99),
 (7, 38, '2009-02-01 00:00:00', 'Barbarossastraße 19', 'Berlin', None, 'Germany', '10779', 1.98),
 (8, 40, '2009-02-01 00:00:00', '8, Rue Hanovre', 'Paris', None, 'France', '75002', 1.98),
 (9, 42, '2009-02-02 00:00:00', '9, Place Louis Barthou', 'Bordeaux', None, 'France', '33000', 3.96),
 (10, 46, '2009-02-03 00:00:00', '3 Chatham Street', 'Dublin', 'Dublin', 'Ireland', None, 5.94)]

In [13]:
%%sql
SELECT
    CustomerId,
    BillingCountry,
    ROUND(Total/SUM(Total) OVER (PARTITION BY BillingCountry)*100,2) AS pct_invoice_bill_by_country
FROM invoices
WHERE BillingCountry IS NOT NULL;

 * sqlite:///chinook.db
Done.

[(56, 'Argentina', 5.26),
 (56, 'Argentina', 10.53),
 (56, 'Argentina', 15.79),
 (56, 'Argentina', 2.63),
 (56, 'Argentina', 5.26),
 (56, 'Argentina', 36.84),
 (56, 'Argentina', 23.68),
 (55, 'Australia', 5.26),
 (55, 'Australia', 10.53),
 (55, 'Australia', 15.79),
 (55, 'Australia', 2.63),
 (55, 'Australia', 5.26),
 (55, 'Australia', 36.84),
 (55, 'Australia', 23.68),
 (7, 'Austria', 4.65),
 (7, 'Austria', 44.25),
 (7, 'Austria', 20.91),
 (7, 'Austria', 4.65),
 (7, 'Austria', 9.29),
 (7, 'Austria', 13.94),
 (7, 'Austria', 2.32),
 (8, 'Belgium', 15.79),
 (8, 'Belgium', 2.63),
 (8, 'Belgium', 5.26),
 (8, 'Belgium', 36.84),
 (8, 'Belgium', 23.68),
 (8, 'Belgium', 5.26),
 (8, 'Belgium', 10.53),
 (10, 'Brazil', 4.69),
 (12, 'Brazil', 0.52),
 (13, 'Brazil', 1.04),
 (11, 'Brazil', 1.04),
 (13, 'Brazil', 2.08),
 (11, 'Brazil', 7.29),
 (13, 'Brazil', 3.12),
 (1, 'Brazil', 2.09),
 (1, 'Brazil', 2.08),
 (11, 'Brazil', 4.69),
 (13, 'Brazil', 0.52),
 (1, 'Brazil', 3.12),
 (10, 'Brazil', 1.04),
 (12, 'Brazil', 1.04),
 (12, 'Brazil', 7.29),
 (10, 'Brazil', 2.08),
 (1, 'Brazil', 0.52),
 (10, 'Brazil', 3.12),
 (12, 'Brazil', 4.69),
 (10, 'Brazil', 0.52),
 (11, 'Brazil', 1.04),
 (13, 'Brazil', 1.04),
 (13, 'Brazil', 7.29),
 (11, 'Brazil', 2.08),
 (11, 'Brazil', 3.12),
 (1, 'Brazil', 1.04),
 (13, 'Brazil', 4.69),
 (1, 'Brazil', 7.29),
 (11, 'Brazil', 0.52),
 (12, 'Brazil', 1.04),
 (10, 'Brazil', 1.04),
 (12, 'Brazil', 2.08),
 (1, 'Brazil', 4.69),
 (10, 'Brazil', 7.29),
 (12, 'Brazil', 3.12),
 (14, 'Canada', 2.93),
 (31, 'Canada', 2.93),
 (33, 'Canada', 0.33),
 (15, 'Canada', 0.65),
 (15, 'Canada', 4.56),
 (29, 'Canada', 0.33),
 (30, 'Canada', 0.65),
 (32, 'Canada', 0.65),
 (32, 'Canada', 4.56),
 (30, 'Canada', 1.3),
 (30, 'Canada', 1.95),
 (3, 'Canada', 1.31),
 (15, 'Canada', 3.26),
 (3, 'Canada', 4.56),
 (32, 'Canada', 2.93),
 (14, 'Canada', 0.65),
 (30, 'Canada', 0.33),
 (31, 'Canada', 0.65),
 (33, 'Canada', 0.65),
 (14, 'Canada', 1.3),
 (33, 'Canada', 4.56),
 (3, 'Canada', 2.93),
 (29, 'Canada', 0.65),
 (31, 'Canada', 1.3),
 (14, 'Canada', 1.95),
 (29, 'Canada', 4.56),
 (31, 'Canada', 1.95),
 (33, 'Canada', 2.93),
 (14, 'Canada', 0.33),
 (15, 'Canada', 0.65),
 (29, 'Canada', 2.93),
 (31, 'Canada', 0.33),
 (32, 'Canada', 0.65),
 (15, 'Canada', 1.3),
 (30, 'Canada', 0.65),
 (32, 'Canada', 1.3),
 (15, 'Canada', 1.95),
 (30, 'Canada', 4.56),
 (32, 'Canada', 1.95),
 (3, 'Canada', 0.65),
 (3, 'Canada', 1.3),
 (15, 'Canada', 0.33),
 (30, 'Canada', 2.93),
 (3, 'Canada', 1.95),
 (32, 'Canada', 0.33),
 (33, 'Canada', 0.65),
 (14, 'Canada', 0.65),
 (14, 'Canada', 4.56),
 (29, 'Canada', 0.65),
 (31, 'Canada', 0.65),
 (33, 'Canada', 1.3),
 (31, 'Canada', 4.56),
 (29, 'Canada', 1.3),
 (33, 'Canada', 1.95),
 (3, 'Canada', 0.33),
 (29, 'Canada', 1.95),
 (57, 'Chile', 4.25),
 (57, 'Chile', 29.73),
 (57, 'Chile', 38.42),
 (57, 'Chile', 4.25),
 (57, 'Chile', 8.49),
 (57, 'Chile', 12.74),
 (57, 'Chile', 2.12),
 (6, 'Czech Republic', 9.87),
 (5, 'Czech Republic', 2.19),
 (5, 'Czech Republic', 4.39),
 (5, 'Czech Republic', 6.58),
 (5, 'Czech Republic', 1.1),
 (6, 'Czech Republic', 2.19),
 (6, 'Czech Republic', 4.39),
 (6, 'Czech Republic', 6.58),
 (6, 'Czech Republic', 1.1),
 (5, 'Czech Republic', 2.19),
 (5, 'Czech Republic', 18.68),
 (5, 'Czech Republic', 9.87),
 (6, 'Czech Republic', 2.19),
 (6, 'Czech Republic', 28.66),
 (9, 'Denmark', 5.26),
 (9, 'Denmark', 10.53),
 (9, 'Denmark', 15.79),
 (9, 'Denmark', 2.63),
 (9, 'Denmark', 5.26),
 (9, 'Denmark', 36.84),
 (9, 'Denmark', 23.68),
 (44, 'Finland', 21.41),
 (44, 'Finland', 4.76),
 (44, 'Finland', 19.13),
 (44, 'Finland', 14.27),
 (44, 'Finland', 2.38),
 (44, 'Finland', 4.76),
 (44, 'Finland', 33.3),
 (40, 'France', 1.01),
 (42, 'France', 2.03),
 (40, 'France', 7.1),
 (42, 'France', 3.04),
 (40, 'France', 4.57),
 (42, 'France', 0.51),
 (43, 'France', 1.01),
 (39, 'France', 1.01),
 (41, 'France', 1.01),
 (43, 'France', 2.03),
 (41, 'France', 7.1),
 (39, 'France', 2.03),
 (43, 'France', 3.04),
 (39, 'France', 3.04),
 (41, 'France', 4.57),
 (43, 'France', 0.51),
 (39, 'France', 1.02),
 (40, 'France', 1.53),
 (42, 'France', 2.04),
 (42, 'France', 7.1),
 (40, 'France', 2.03),
 (40, 'France', 3.04),
 (42, 'France', 4.57),
 (40, 'France', 0.51),
 (41, 'France', 1.01),
 (43, 'France', 1.01),
 (43, 'France', 8.64),
 (39, 'France', 1.01),
 (41, 'France', 2.03),
 (39, 'France', 7.1),
 (41, 'France', 3.04),
 (43, 'France', 4.57),
 (39, 'France', 4.57),
 (41, 'France', 0.51),
 (42, 'France', 1.01),
 (2, 'Germany', 1.27),
 (37, 'Germany', 0.63),
 (38, 'Germany', 1.27),
 (2, 'Germany', 8.86),
 (36, 'Germany', 1.27),
 (38, 'Germany', 2.53),
 (36, 'Germany', 8.86),
 (38, 'Germany', 3.8),
 (2, 'Germany', 5.69),
 (36, 'Germany', 5.69),
 (38, 'Germany', 0.63),
 (37, 'Germany', 1.27),
 (37, 'Germany', 8.86),
 (37, 'Germany', 9.53),
 (2, 'Germany', 1.27),
 (2, 'Germany', 2.53),
 (36, 'Germany', 1.27),
 (38, 'Germany', 1.27),
 (38, 'Germany', 8.86),
 (2, 'Germany', 3.8),
 (36, 'Germany', 2.53),
 (36, 'Germany', 3.8),
 (38, 'Germany', 5.69),
 (2, 'Germany', 0.63),
 (36, 'Germany', 0.63),
 (37, 'Germany', 1.27),
 (37, 'Germany', 2.53),
 (37, 'Germany', 3.8),
 (45, 'Hungary', 4.34),
 (45, 'Hungary', 47.92),
 (45, 'Hungary', 19.53),
 (45, 'Hungary', 4.34),
 (45, 'Hungary', 8.68),
 (45, 'Hungary', 13.02),
 (45, 'Hungary', 2.17),
 (59, 'India', 5.26),
 (59, 'India', 7.89),
 (59, 'India', 2.64),
 (58, 'India', 2.63),
 (58, 'India', 18.42),
 (58, 'India', 11.84),
 (59, 'India', 2.63),
 (59, 'India', 18.42),
 (59, 'India', 11.84),
 (58, 'India', 2.63),
 (58, 'India', 5.26),
 (58, 'India', 7.89),
 (58, 'India', 2.64),
 (46, 'Ireland', 13.02),
 (46, 'Ireland', 2.17),
 (46, 'Ireland', 4.34),
 (46, 'Ireland', 47.92),
 (46, 'Ireland', 19.53),
 (46, 'Ireland', 4.34),
 (46, 'Ireland', 8.68),
 (47, 'Italy', 5.26),
 (47, 'Italy', 10.53),
 (47, 'Italy', 15.79),
 (47, 'Italy', 2.63),
 (47, 'Italy', 5.26),
 (47, 'Italy', 36.84),
 (47, 'Italy', 23.68),
 (48, 'Netherlands', 21.94),
 (48, 'Netherlands', 4.87),
 (48, 'Netherlands', 9.75),
 (48, 'Netherlands', 22.01),
 (48, 'Netherlands', 2.44),
 (48, 'Netherlands', 4.87),
 (48, 'Netherlands', 34.12),
 (4, 'Norway', 9.99),
 (4, 'Norway', 14.99),
 (4, 'Norway', 2.5),
 (4, 'Norway', 5.0),
 (4, 'Norway', 40.03),
 (4, 'Norway', 22.49),
 (4, 'Norway', 5.0),
 (49, 'Poland', 5.26),
 (49, 'Poland', 36.84),
 (49, 'Poland', 23.68),
 (49, 'Poland', 5.26),
 (49, 'Poland', 10.53),
 (49, 'Poland', 15.79),
 (49, 'Poland', 2.63),
 (34, 'Portugal', 2.56),
 (34, 'Portugal', 5.13),
 (34, 'Portugal', 7.69),
 (34, 'Portugal', 1.28),
 (35, 'Portugal', 2.56),
 (35, 'Portugal', 5.13),
 (35, 'Portugal', 7.69),
 (35, 'Portugal', 1.28),
 (34, 'Portugal', 2.56),
 (34, 'Portugal', 17.94),
 (34, 'Portugal', 14.12),
 (35, 'Portugal', 2.56),
 (35, 'Portugal', 17.94),
 (35, 'Portugal', 11.54),
 (50, 'Spain', 2.63),
 (50, 'Spain', 5.26),
 (50, 'Spain', 36.84),
 (50, 'Spain', 23.68),
 (50, 'Spain', 5.26),
 (50, 'Spain', 10.53),
 (50, 'Spain', 15.79),
 (51, 'Sweden', 5.13),
 (51, 'Sweden', 10.25),
 (51, 'Sweden', 17.97),
 (51, 'Sweden', 2.56),
 (51, 'Sweden', 5.13),
 (51, 'Sweden', 35.89),
 (51, 'Sweden', 23.07),
 (23, 'USA', 2.65),
 (16, 'USA', 0.19),
 (17, 'USA', 0.38),
 (19, 'USA', 0.38),
 (21, 'USA', 0.76),
 (25, 'USA', 1.14),
 (19, 'USA', 2.65),
 (17, 'USA', 0.76),
 (21, 'USA', 1.14),
 (27, 'USA', 1.7),
 (17, 'USA', 1.14),
 (23, 'USA', 1.7),
 (25, 'USA', 0.19),
 (26, 'USA', 0.38),
 (28, 'USA', 0.38),
 (19, 'USA', 1.7),
 (28, 'USA', 2.65),
 (21, 'USA', 0.19),
 (22, 'USA', 0.38),
 (24, 'USA', 0.38),
 (26, 'USA', 0.76),
 (24, 'USA', 3.03),
 (17, 'USA', 0.19),
 (18, 'USA', 0.38),
 (20, 'USA', 0.38),
 (22, 'USA', 0.76),
 (26, 'USA', 1.14),
 (20, 'USA', 2.65),
 (16, 'USA', 0.38),
 (18, 'USA', 0.76),
 (22, 'USA', 1.14),
 (28, 'USA', 1.7),
 (16, 'USA', 2.65),
 (18, 'USA', 1.14),
 (24, 'USA', 1.7),
 (26, 'USA', 0.19),
 (27, 'USA', 0.38),
 (20, 'USA', 1.7),
 (22, 'USA', 0.19),
 (23, 'USA', 0.38),
 (25, 'USA', 0.38),
 (27, 'USA', 0.76),
 (16, 'USA', 1.7),
 (25, 'USA', 3.61),
 (18, 'USA', 0.19),
 (19, 'USA', 0.38),
 (21, 'USA', 0.38),
 (23, 'USA', 0.76),
 (27, 'USA', 1.14),
 (21, 'USA', 2.65),
 (17, 'USA', 0.38),
 (19, 'USA', 0.76),
 (23, 'USA', 1.14),
 (17, 'USA', 2.65),
 (19, 'USA', 1.14),
 (25, 'USA', 1.7),
 (27, 'USA', 0.19),
 (28, 'USA', 0.38),
 (21, 'USA', 1.7),
 (23, 'USA', 0.19),
 (24, 'USA', 0.38),
 (26, 'USA', 0.38),
 (28, 'USA', 0.76),
 (17, 'USA', 2.09),
 (26, 'USA', 4.56),
 (19, 'USA', 0.38),
 (20, 'USA', 0.76),
 (22, 'USA', 0.76),
 (24, 'USA', 1.52),
 (28, 'USA', 2.28),
 (22, 'USA', 2.65),
 (16, 'USA', 0.38),
 (18, 'USA', 0.38),
 (20, 'USA', 0.76),
 (24, 'USA', 1.14),
 (18, 'USA', 2.65),
 (16, 'USA', 0.76),
 (20, 'USA', 1.14),
 (26, 'USA', 1.7),
 (28, 'USA', 0.19),
 (16, 'USA', 1.14),
 (22, 'USA', 1.7),
 (24, 'USA', 0.19),
 (25, 'USA', 0.38),
 (27, 'USA', 0.38),
 (18, 'USA', 1.7),
 (27, 'USA', 2.65),
 (20, 'USA', 0.19),
 (21, 'USA', 0.38),
 (23, 'USA', 0.38),
 (25, 'USA', 0.76),
 (52, 'United Kingdom', 7.89),
 (54, 'United Kingdom', 0.88),
 (53, 'United Kingdom', 1.75),
 (53, 'United Kingdom', 12.28),
 (53, 'United Kingdom', 7.89),
 (52, 'United Kingdom', 1.75),
 (54, 'United Kingdom', 1.75),
 (54, 'United Kingdom', 12.28),
 (52, 'United Kingdom', 3.51),
 (52, 'United Kingdom', 5.26),
 (54, 'United Kingdom', 7.89),
 (52, 'United Kingdom', 0.88),
 (53, 'United Kingdom', 1.75),
 (53, 'United Kingdom', 3.51),
 (53, 'United Kingdom', 5.26),
 (53, 'United Kingdom', 0.88),
 (54, 'United Kingdom', 1.75),
 (52, 'United Kingdom', 1.75),
 (54, 'United Kingdom', 3.51),
 (52, 'United Kingdom', 12.28),
 (54, 'United Kingdom', 5.26)]

In [18]:
%%sql
SELECT 
    CustomerId,
    BillingCountry,
    ROUND(AVG(Total) OVER (PARTITION BY BillingCountry ORDER BY BillingCountry),2) AS Avg_Invoice_Amount
FROM invoices
WHERE Total IS NOT NULL;

 * sqlite:///chinook.db
Done.

[(56, 'Argentina', 5.37),
 (56, 'Argentina', 5.37),
 (56, 'Argentina', 5.37),
 (56, 'Argentina', 5.37),
 (56, 'Argentina', 5.37),
 (56, 'Argentina', 5.37),
 (56, 'Argentina', 5.37),
 (55, 'Australia', 5.37),
 (55, 'Australia', 5.37),
 (55, 'Australia', 5.37),
 (55, 'Australia', 5.37),
 (55, 'Australia', 5.37),
 (55, 'Australia', 5.37),
 (55, 'Australia', 5.37),
 (7, 'Austria', 6.09),
 (7, 'Austria', 6.09),
 (7, 'Austria', 6.09),
 (7, 'Austria', 6.09),
 (7, 'Austria', 6.09),
 (7, 'Austria', 6.09),
 (7, 'Austria', 6.09),
 (8, 'Belgium', 5.37),
 (8, 'Belgium', 5.37),
 (8, 'Belgium', 5.37),
 (8, 'Belgium', 5.37),
 (8, 'Belgium', 5.37),
 (8, 'Belgium', 5.37),
 (8, 'Belgium', 5.37),
 (10, 'Brazil', 5.43),
 (12, 'Brazil', 5.43),
 (13, 'Brazil', 5.43),
 (11, 'Brazil', 5.43),
 (13, 'Brazil', 5.43),
 (11, 'Brazil', 5.43),
 (13, 'Brazil', 5.43),
 (1, 'Brazil', 5.43),
 (1, 'Brazil', 5.43),
 (11, 'Brazil', 5.43),
 (13, 'Brazil', 5.43),
 (1, 'Brazil', 5.43),
 (10, 'Brazil', 5.43),
 (12, 'Brazil', 5.43),
 (12, 'Brazil', 5.43),
 (10, 'Brazil', 5.43),
 (1, 'Brazil', 5.43),
 (10, 'Brazil', 5.43),
 (12, 'Brazil', 5.43),
 (10, 'Brazil', 5.43),
 (11, 'Brazil', 5.43),
 (13, 'Brazil', 5.43),
 (13, 'Brazil', 5.43),
 (11, 'Brazil', 5.43),
 (11, 'Brazil', 5.43),
 (1, 'Brazil', 5.43),
 (13, 'Brazil', 5.43),
 (1, 'Brazil', 5.43),
 (11, 'Brazil', 5.43),
 (12, 'Brazil', 5.43),
 (10, 'Brazil', 5.43),
 (12, 'Brazil', 5.43),
 (1, 'Brazil', 5.43),
 (10, 'Brazil', 5.43),
 (12, 'Brazil', 5.43),
 (14, 'Canada', 5.43),
 (31, 'Canada', 5.43),
 (33, 'Canada', 5.43),
 (15, 'Canada', 5.43),
 (15, 'Canada', 5.43),
 (29, 'Canada', 5.43),
 (30, 'Canada', 5.43),
 (32, 'Canada', 5.43),
 (32, 'Canada', 5.43),
 (30, 'Canada', 5.43),
 (30, 'Canada', 5.43),
 (3, 'Canada', 5.43),
 (15, 'Canada', 5.43),
 (3, 'Canada', 5.43),
 (32, 'Canada', 5.43),
 (14, 'Canada', 5.43),
 (30, 'Canada', 5.43),
 (31, 'Canada', 5.43),
 (33, 'Canada', 5.43),
 (14, 'Canada', 5.43),
 (33, 'Canada', 5.43),
 (3, 'Canada', 5.43),
 (29, 'Canada', 5.43),
 (31, 'Canada', 5.43),
 (14, 'Canada', 5.43),
 (29, 'Canada', 5.43),
 (31, 'Canada', 5.43),
 (33, 'Canada', 5.43),
 (14, 'Canada', 5.43),
 (15, 'Canada', 5.43),
 (29, 'Canada', 5.43),
 (31, 'Canada', 5.43),
 (32, 'Canada', 5.43),
 (15, 'Canada', 5.43),
 (30, 'Canada', 5.43),
 (32, 'Canada', 5.43),
 (15, 'Canada', 5.43),
 (30, 'Canada', 5.43),
 (32, 'Canada', 5.43),
 (3, 'Canada', 5.43),
 (3, 'Canada', 5.43),
 (15, 'Canada', 5.43),
 (30, 'Canada', 5.43),
 (3, 'Canada', 5.43),
 (32, 'Canada', 5.43),
 (33, 'Canada', 5.43),
 (14, 'Canada', 5.43),
 (14, 'Canada', 5.43),
 (29, 'Canada', 5.43),
 (31, 'Canada', 5.43),
 (33, 'Canada', 5.43),
 (31, 'Canada', 5.43),
 (29, 'Canada', 5.43),
 (33, 'Canada', 5.43),
 (3, 'Canada', 5.43),
 (29, 'Canada', 5.43),
 (57, 'Chile', 6.66),
 (57, 'Chile', 6.66),
 (57, 'Chile', 6.66),
 (57, 'Chile', 6.66),
 (57, 'Chile', 6.66),
 (57, 'Chile', 6.66),
 (57, 'Chile', 6.66),
 (6, 'Czech Republic', 6.45),
 (5, 'Czech Republic', 6.45),
 (5, 'Czech Republic', 6.45),
 (5, 'Czech Republic', 6.45),
 (5, 'Czech Republic', 6.45),
 (6, 'Czech Republic', 6.45),
 (6, 'Czech Republic', 6.45),
 (6, 'Czech Republic', 6.45),
 (6, 'Czech Republic', 6.45),
 (5, 'Czech Republic', 6.45),
 (5, 'Czech Republic', 6.45),
 (5, 'Czech Republic', 6.45),
 (6, 'Czech Republic', 6.45),
 (6, 'Czech Republic', 6.45),
 (9, 'Denmark', 5.37),
 (9, 'Denmark', 5.37),
 (9, 'Denmark', 5.37),
 (9, 'Denmark', 5.37),
 (9, 'Denmark', 5.37),
 (9, 'Denmark', 5.37),
 (9, 'Denmark', 5.37),
 (44, 'Finland', 5.95),
 (44, 'Finland', 5.95),
 (44, 'Finland', 5.95),
 (44, 'Finland', 5.95),
 (44, 'Finland', 5.95),
 (44, 'Finland', 5.95),
 (44, 'Finland', 5.95),
 (40, 'France', 5.57),
 (42, 'France', 5.57),
 (40, 'France', 5.57),
 (42, 'France', 5.57),
 (40, 'France', 5.57),
 (42, 'France', 5.57),
 (43, 'France', 5.57),
 (39, 'France', 5.57),
 (41, 'France', 5.57),
 (43, 'France', 5.57),
 (41, 'France', 5.57),
 (39, 'France', 5.57),
 (43, 'France', 5.57),
 (39, 'France', 5.57),
 (41, 'France', 5.57),
 (43, 'France', 5.57),
 (39, 'France', 5.57),
 (40, 'France', 5.57),
 (42, 'France', 5.57),
 (42, 'France', 5.57),
 (40, 'France', 5.57),
 (40, 'France', 5.57),
 (42, 'France', 5.57),
 (40, 'France', 5.57),
 (41, 'France', 5.57),
 (43, 'France', 5.57),
 (43, 'France', 5.57),
 (39, 'France', 5.57),
 (41, 'France', 5.57),
 (39, 'France', 5.57),
 (41, 'France', 5.57),
 (43, 'France', 5.57),
 (39, 'France', 5.57),
 (41, 'France', 5.57),
 (42, 'France', 5.57),
 (2, 'Germany', 5.59),
 (37, 'Germany', 5.59),
 (38, 'Germany', 5.59),
 (2, 'Germany', 5.59),
 (36, 'Germany', 5.59),
 (38, 'Germany', 5.59),
 (36, 'Germany', 5.59),
 (38, 'Germany', 5.59),
 (2, 'Germany', 5.59),
 (36, 'Germany', 5.59),
 (38, 'Germany', 5.59),
 (37, 'Germany', 5.59),
 (37, 'Germany', 5.59),
 (37, 'Germany', 5.59),
 (2, 'Germany', 5.59),
 (2, 'Germany', 5.59),
 (36, 'Germany', 5.59),
 (38, 'Germany', 5.59),
 (38, 'Germany', 5.59),
 (2, 'Germany', 5.59),
 (36, 'Germany', 5.59),
 (36, 'Germany', 5.59),
 (38, 'Germany', 5.59),
 (2, 'Germany', 5.59),
 (36, 'Germany', 5.59),
 (37, 'Germany', 5.59),
 (37, 'Germany', 5.59),
 (37, 'Germany', 5.59),
 (45, 'Hungary', 6.52),
 (45, 'Hungary', 6.52),
 (45, 'Hungary', 6.52),
 (45, 'Hungary', 6.52),
 (45, 'Hungary', 6.52),
 (45, 'Hungary', 6.52),
 (45, 'Hungary', 6.52),
 (59, 'India', 5.79),
 (59, 'India', 5.79),
 (59, 'India', 5.79),
 (58, 'India', 5.79),
 (58, 'India', 5.79),
 (58, 'India', 5.79),
 (59, 'India', 5.79),
 (59, 'India', 5.79),
 (59, 'India', 5.79),
 (58, 'India', 5.79),
 (58, 'India', 5.79),
 (58, 'India', 5.79),
 (58, 'India', 5.79),
 (46, 'Ireland', 6.52),
 (46, 'Ireland', 6.52),
 (46, 'Ireland', 6.52),
 (46, 'Ireland', 6.52),
 (46, 'Ireland', 6.52),
 (46, 'Ireland', 6.52),
 (46, 'Ireland', 6.52),
 (47, 'Italy', 5.37),
 (47, 'Italy', 5.37),
 (47, 'Italy', 5.37),
 (47, 'Italy', 5.37),
 (47, 'Italy', 5.37),
 (47, 'Italy', 5.37),
 (47, 'Italy', 5.37),
 (48, 'Netherlands', 5.8),
 (48, 'Netherlands', 5.8),
 (48, 'Netherlands', 5.8),
 (48, 'Netherlands', 5.8),
 (48, 'Netherlands', 5.8),
 (48, 'Netherlands', 5.8),
 (48, 'Netherlands', 5.8),
 (4, 'Norway', 5.66),
 (4, 'Norway', 5.66),
 (4, 'Norway', 5.66),
 (4, 'Norway', 5.66),
 (4, 'Norway', 5.66),
 (4, 'Norway', 5.66),
 (4, 'Norway', 5.66),
 (49, 'Poland', 5.37),
 (49, 'Poland', 5.37),
 (49, 'Poland', 5.37),
 (49, 'Poland', 5.37),
 (49, 'Poland', 5.37),
 (49, 'Poland', 5.37),
 (49, 'Poland', 5.37),
 (34, 'Portugal', 5.52),
 (34, 'Portugal', 5.52),
 (34, 'Portugal', 5.52),
 (34, 'Portugal', 5.52),
 (35, 'Portugal', 5.52),
 (35, 'Portugal', 5.52),
 (35, 'Portugal', 5.52),
 (35, 'Portugal', 5.52),
 (34, 'Portugal', 5.52),
 (34, 'Portugal', 5.52),
 (34, 'Portugal', 5.52),
 (35, 'Portugal', 5.52),
 (35, 'Portugal', 5.52),
 (35, 'Portugal', 5.52),
 (50, 'Spain', 5.37),
 (50, 'Spain', 5.37),
 (50, 'Spain', 5.37),
 (50, 'Spain', 5.37),
 (50, 'Spain', 5.37),
 (50, 'Spain', 5.37),
 (50, 'Spain', 5.37),
 (51, 'Sweden', 5.52),
 (51, 'Sweden', 5.52),
 (51, 'Sweden', 5.52),
 (51, 'Sweden', 5.52),
 (51, 'Sweden', 5.52),
 (51, 'Sweden', 5.52),
 (51, 'Sweden', 5.52),
 (23, 'USA', 5.75),
 (16, 'USA', 5.75),
 (17, 'USA', 5.75),
 (19, 'USA', 5.75),
 (21, 'USA', 5.75),
 (25, 'USA', 5.75),
 (19, 'USA', 5.75),
 (17, 'USA', 5.75),
 (21, 'USA', 5.75),
 (27, 'USA', 5.75),
 (17, 'USA', 5.75),
 (23, 'USA', 5.75),
 (25, 'USA', 5.75),
 (26, 'USA', 5.75),
 (28, 'USA', 5.75),
 (19, 'USA', 5.75),
 (28, 'USA', 5.75),
 (21, 'USA', 5.75),
 (22, 'USA', 5.75),
 (24, 'USA', 5.75),
 (26, 'USA', 5.75),
 (24, 'USA', 5.75),
 (17, 'USA', 5.75),
 (18, 'USA', 5.75),
 (20, 'USA', 5.75),
 (22, 'USA', 5.75),
 (26, 'USA', 5.75),
 (20, 'USA', 5.75),
 (16, 'USA', 5.75),
 (18, 'USA', 5.75),
 (22, 'USA', 5.75),
 (28, 'USA', 5.75),
 (16, 'USA', 5.75),
 (18, 'USA', 5.75),
 (24, 'USA', 5.75),
 (26, 'USA', 5.75),
 (27, 'USA', 5.75),
 (20, 'USA', 5.75),
 (22, 'USA', 5.75),
 (23, 'USA', 5.75),
 (25, 'USA', 5.75),
 (27, 'USA', 5.75),
 (16, 'USA', 5.75),
 (25, 'USA', 5.75),
 (18, 'USA', 5.75),
 (19, 'USA', 5.75),
 (21, 'USA', 5.75),
 (23, 'USA', 5.75),
 (27, 'USA', 5.75),
 (21, 'USA', 5.75),
 (17, 'USA', 5.75),
 (19, 'USA', 5.75),
 (23, 'USA', 5.75),
 (17, 'USA', 5.75),
 (19, 'USA', 5.75),
 (25, 'USA', 5.75),
 (27, 'USA', 5.75),
 (28, 'USA', 5.75),
 (21, 'USA', 5.75),
 (23, 'USA', 5.75),
 (24, 'USA', 5.75),
 (26, 'USA', 5.75),
 (28, 'USA', 5.75),
 (17, 'USA', 5.75),
 (26, 'USA', 5.75),
 (19, 'USA', 5.75),
 (20, 'USA', 5.75),
 (22, 'USA', 5.75),
 (24, 'USA', 5.75),
 (28, 'USA', 5.75),
 (22, 'USA', 5.75),
 (16, 'USA', 5.75),
 (18, 'USA', 5.75),
 (20, 'USA', 5.75),
 (24, 'USA', 5.75),
 (18, 'USA', 5.75),
 (16, 'USA', 5.75),
 (20, 'USA', 5.75),
 (26, 'USA', 5.75),
 (28, 'USA', 5.75),
 (16, 'USA', 5.75),
 (22, 'USA', 5.75),
 (24, 'USA', 5.75),
 (25, 'USA', 5.75),
 (27, 'USA', 5.75),
 (18, 'USA', 5.75),
 (27, 'USA', 5.75),
 (20, 'USA', 5.75),
 (21, 'USA', 5.75),
 (23, 'USA', 5.75),
 (25, 'USA', 5.75),
 (52, 'United Kingdom', 5.37),
 (54, 'United Kingdom', 5.37),
 (53, 'United Kingdom', 5.37),
 (53, 'United Kingdom', 5.37),
 (53, 'United Kingdom', 5.37),
 (52, 'United Kingdom', 5.37),
 (54, 'United Kingdom', 5.37),
 (54, 'United Kingdom', 5.37),
 (52, 'United Kingdom', 5.37),
 (52, 'United Kingdom', 5.37),
 (54, 'United Kingdom', 5.37),
 (52, 'United Kingdom', 5.37),
 (53, 'United Kingdom', 5.37),
 (53, 'United Kingdom', 5.37),
 (53, 'United Kingdom', 5.37),
 (53, 'United Kingdom', 5.37),
 (54, 'United Kingdom', 5.37),
 (52, 'United Kingdom', 5.37),
 (54, 'United Kingdom', 5.37),
 (52, 'United Kingdom', 5.37),
 (54, 'United Kingdom', 5.37)]

In [20]:
%%sql
SELECT c.FirstName AS "customer_name", c.LastName AS "customer_surname", e.FirstName AS "agent_name", e.LastName AS "agent_surname"
FROM customers c, employees e
WHERE c.Country = "Canada"
AND c.SupportRepId = e.EmployeeId;

 * sqlite:///chinook.db
Done.

[('François', 'Tremblay', 'Jane', 'Peacock'),
 ('Mark', 'Philips', 'Steve', 'Johnson'),
 ('Jennifer', 'Peterson', 'Jane', 'Peacock'),
 ('Robert', 'Brown', 'Jane', 'Peacock'),
 ('Edward', 'Francis', 'Jane', 'Peacock'),
 ('Martha', 'Silk', 'Steve', 'Johnson'),
 ('Aaron', 'Mitchell', 'Margaret', 'Park'),
 ('Ellie', 'Sullivan', 'Jane', 'Peacock')]

In [28]:
%%sql

CREATE TABLE canadianemployees (
  FirstName VARCHAR(50),
  LastName VARCHAR(50),
  AgentName VARCHAR(50),
  AgentSurname VARCHAR(50)
);

 * sqlite:///chinook.db
(sqlite3.OperationalError) table canadianemployees already exists
[SQL: CREATE TABLE canadianemployees (
  FirstName VARCHAR(50),
  LastName VARCHAR(50),
  AgentName VARCHAR(50),
  AgentSurname VARCHAR(50)
);]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

In [29]:
%%sql

INSERT INTO canadianemployees (FirstName, LastName, AgentName, AgentSurname)
SELECT c.FirstName AS "customer_name", c.LastName AS "customer_surname", e.FirstName AS "agent_name", e.LastName AS "agent_surname"
FROM customers c, employees e
WHERE c.Country = "Canada"
AND c.SupportRepId = e.EmployeeId;

 * sqlite:///chinook.db
8 rows affected.

[]

In [30]:
%sql SELECT * FROM canadianemployees;

 * sqlite:///chinook.db
Done.

[('François', 'Tremblay', 'Jane', 'Peacock'),
 ('Mark', 'Philips', 'Steve', 'Johnson'),
 ('Jennifer', 'Peterson', 'Jane', 'Peacock'),
 ('Robert', 'Brown', 'Jane', 'Peacock'),
 ('Edward', 'Francis', 'Jane', 'Peacock'),
 ('Martha', 'Silk', 'Steve', 'Johnson'),
 ('Aaron', 'Mitchell', 'Margaret', 'Park'),
 ('Ellie', 'Sullivan', 'Jane', 'Peacock')]